In [3]:
import pandas as pd
# завантаження
df = pd.read_csv("Downloads/stack-overflow-developer-survey-2024/survey_results_public.csv")
schema = pd.read_csv("Downloads/stack-overflow-developer-survey-2024/survey_results_schema.csv")
df.head()

,ResponseId,MainBranch,Age,Employment,RemoteWork,Check,CodingActivities,EdLevel,LearnCode,LearnCodeOnline,...,JobSatPoints_6,JobSatPoints_7,JobSatPoints_8,JobSatPoints_9,JobSatPoints_10,JobSatPoints_11,SurveyLength,SurveyEase,ConvertedCompYearly,JobSat
0,1,I am a developer by profession,Under 18 years old,"Employed, full-time",Remote,Apples,Hobby,Primary/elementary school,Books / Physical media,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,I am a developer by profession,35-44 years old,"Employed, full-time",Remote,Apples,Hobby;Contribute to open-source projects;Other...,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Books / Physical media;Colleague;On the job tr...,Technical documentation;Blogs;Books;Written Tu...,...,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN
2,3,I am a developer by profession,45-54 years old,"Employed, full-time",Remote,Apples,Hobby;Contribute to open-source projects;Other...,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Books / Physical media;Colleague;On the job tr...,Technical documentation;Blogs;Books;Written Tu...,...,NaN,NaN,NaN,NaN,NaN,NaN,Appropriate in length,Easy,NaN,NaN
3,4,I am learning to code,18-24 years old,"Student, full-time",NaN,Apples,NaN,Some college/university study without earning ...,"Other online resources (e.g., videos, blogs, f...",Stack Overflow;How-to videos;Interactive tutorial,...,NaN,NaN,NaN,NaN,NaN,NaN,Too long,Easy,NaN,NaN
4,5,I am a developer by profession,18-24 years old,"Student, full-time",NaN,Apples,NaN,"Secondary school (e.g. American high school, G...","Other online resources (e.g., videos, blogs, f...",Technical documentation;Blogs;Written Tutorial...,...,NaN,NaN,NaN,NaN,NaN,NaN,Too short,Easy,NaN,NaN

In [5]:
import pandas as pd
# завантаження
df = pd.read_csv("Downloads/stack-overflow-developer-survey-2024/survey_results_public.csv")
schema = pd.read_csv("Downloads/stack-overflow-developer-survey-2024/survey_results_schema.csv")
schema.head()

,qid,qname,question,force_resp,type,selector
0,QID2,MainBranch,Which of the following options best describes ...,True,MC,SAVR
1,QID127,Age,What is your age?*,True,MC,SAVR
2,QID296,Employment,Which of the following best describes your cur...,True,MC,MAVR
3,QID308,RemoteWork,Which best describes your current work situation?,False,MC,SAVR
4,QID341,Check,Just checking to make sure you are paying atte...,True,MC,SAVR

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 65437 entries, 0 to 65436
Columns: 114 entries, ResponseId to JobSat
dtypes: float64(13), int64(1), object(100)
memory usage: 56.9+ MB

In [10]:
schema.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 87 entries, 0 to 86
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   qid         87 non-null     object
 1   qname       87 non-null     object
 2   question    87 non-null     object
 3   force_resp  66 non-null     object
 4   type        87 non-null     object
 5   selector    87 non-null     object
dtypes: object(6)
memory usage: 4.2+ KB

In [7]:
# Завдання 1

df.shape[0]

65437

In [21]:
# Завдання 2

# завантаження
df = pd.read_csv("Downloads/stack-overflow-developer-survey-2024/survey_results_public.csv")
schema = pd.read_csv("Downloads/stack-overflow-developer-survey-2024/survey_results_schema.csv")

# список питань (колонок)
questions = schema["qname"]

# залишаємо тільки ті, що є в df
valid_questions = df.columns.intersection(questions)

# респонденти без жодного пропуску
complete_responses = df[valid_questions].notna().all(axis=1)

# кількість таких респондентів
complete_responses.sum()

np.int64(6306)

In [22]:
# Завдання 3

import pandas as pd

df = pd.read_csv("Downloads/stack-overflow-developer-survey-2024/survey_results_public.csv")

# перетворення в число (про всяк випадок)
work_exp = pd.to_numeric(df["WorkExp"], errors="coerce")

# обчислення метрик
mean_val = work_exp.mean()
median_val = work_exp.median()
mode_val = work_exp.mode()[0]

# оформлення результату
result = pd.Series({
    "mean": mean_val,
    "median": median_val,
    "mode": mode_val
})

result

mean      11.466957
median     9.000000
mode       3.000000
dtype: float64

In [24]:
# Завдання 4

import pandas as pd

df = pd.read_csv("Downloads/stack-overflow-developer-survey-2024/survey_results_public.csv")
df["RemoteWork"].value_counts()

RemoteWork
Hybrid (some remote, some in-person)    23015
Remote                                  20831
In-person                               10960
Name: count, dtype: int64

In [25]:
# Завдання 4

import pandas as pd

df = pd.read_csv("Downloads/stack-overflow-developer-survey-2024/survey_results_public.csv")

remote_count = (df["RemoteWork"] == "Remote").sum()

remote_count

np.int64(20831)

In [30]:
# Завдання 5

import pandas as pd

df = pd.read_csv("Downloads/stack-overflow-developer-survey-2024/survey_results_public.csv")

# респонденти, які використовують Python
python_users = df["LanguageHaveWorkedWith"].str.contains("Python", na=False)

# відсоток
percent_python = python_users.mean() * 100

# гарний формат
f"{percent_python:.1f}%"

'47.1%'

In [31]:
# Завдання 6

df["LearnCode"].value_counts().head(10)

LearnCode
Other online resources (e.g., videos, blogs, forum, online community)                                                                                                                       3674
Books / Physical media;Other online resources (e.g., videos, blogs, forum, online community)                                                                                                2493
Other online resources (e.g., videos, blogs, forum, online community);School (i.e., University, College, etc)                                                                               2362
Books / Physical media;Other online resources (e.g., videos, blogs, forum, online community);Online Courses or Certification                                                                2286
Other online resources (e.g., videos, blogs, forum, online community);Online Courses or Certification                                                                                       2182
Books / Physical media;Other online resources (e.g., videos, blogs, forum, online community);School (i.e., University, College, etc)                                                        1925
Books / Physical media;On the job training;Other online resources (e.g., videos, blogs, forum, online community);School (i.e., University, College, etc);Online Courses or Certification    1879
Books / Physical media;Other online resources (e.g., videos, blogs, forum, online community);School (i.e., University, College, etc);Online Courses or Certification                        1629
On the job training;Other online resources (e.g., videos, blogs, forum, online community);Online Courses or Certification                                                                   1600
Books / Physical media;On the job training;Other online resources (e.g., videos, blogs, forum, online community);Online Courses or Certification                                            1568
Name: count, dtype: int64

In [33]:
# Завдання 6

import pandas as pd

df = pd.read_csv("Downloads/stack-overflow-developer-survey-2024/survey_results_public.csv")

online_users = df["LearnCode"].str.contains("Online Courses or Certification", na=False)

online_count = online_users.sum()

online_count

np.int64(30271)

In [34]:
# Завдання 7

import pandas as pd

df = pd.read_csv("Downloads/stack-overflow-developer-survey-2024/survey_results_public.csv")

# 1. Фільтр: тільки Python-розробники
python_df = df[df["LanguageHaveWorkedWith"].str.contains("Python", na=False)]

# 2. Групування по країнах і агрегація
result = python_df.groupby("Country")["ConvertedCompYearly"].agg(
    mean_comp="mean",
    median_comp="median"
).reset_index()

result

                                  Country      mean_comp  median_comp
0                             Afghanistan    4543.000000       4768.5
1                                 Albania   56295.000000      56295.0
2                                 Algeria    9053.285714       6230.0
3                                 Andorra  193331.000000     193331.0
4                                  Angola       6.000000          6.0
..                                    ...            ...          ...
168  Venezuela, Bolivarian Republic of...   21500.000000       7100.0
169                              Viet Nam   14014.562500      10180.0
170                                 Yemen   10297.333333       5333.0
171                                Zambia   28123.666667      22803.0
172                              Zimbabwe   37500.000000      18000.0

[173 rows x 3 columns]

In [35]:
# Завдання 8

import pandas as pd

df = pd.read_csv("Downloads/stack-overflow-developer-survey-2024/survey_results_public.csv")

# 1. прибираємо пропуски в компенсації
df_clean = df.dropna(subset=["ConvertedCompYearly"])

# 2. сортуємо за компенсацією (спадання)
top5 = df_clean.sort_values("ConvertedCompYearly", ascending=False).head(5)

# 3. беремо рівень освіти
top5["EdLevel"]

15837      Bachelor’s degree (B.A., B.S., B.Eng., etc.)
12723    Professional degree (JD, MD, Ph.D, Ed.D, etc.)
28379    Professional degree (JD, MD, Ph.D, Ed.D, etc.)
17593      Bachelor’s degree (B.A., B.S., B.Eng., etc.)
17672    Professional degree (JD, MD, Ph.D, Ed.D, etc.)
Name: EdLevel, dtype: object

In [36]:
# Завдання 9

import pandas as pd

df = pd.read_csv("Downloads/stack-overflow-developer-survey-2024/survey_results_public.csv")

# 1. маска Python-розробників
df["is_python"] = df["LanguageHaveWorkedWith"].str.contains("Python", na=False)

# 2. групування по вікових категоріях
result = df.groupby("Age")["is_python"].mean() * 100

# 3. красивий вигляд
result.sort_values(ascending=False)

Age
Under 18 years old    64.875389
18-24 years old       55.922826
25-34 years old       45.773912
Prefer not to say     45.341615
45-54 years old       41.910706
35-44 years old       41.520546
55-64 years old       40.427184
65 years or older     37.564767
Name: is_python, dtype: float64

In [39]:
# Завдання 10

import pandas as pd

df = pd.read_csv("Downloads/stack-overflow-developer-survey-2024/survey_results_public.csv")

# прибираємо NaN у компенсації
comp = df["ConvertedCompYearly"].dropna()

# 75-й перцентиль
p75 = comp.quantile(0.75)

# фільтр
filtered = df[
    (df["ConvertedCompYearly"] > p75) &
    (df["RemoteWork"] == "Remote")
]

# частота індустрій (з очищенням NaN)
top_industries = filtered["Industry"].value_counts(dropna=True)

top_industries

Industry
Software Development                          768
Other:                                        239
Healthcare                                    156
Fintech                                       156
Internet, Telecomm or Information Services    145
Retail and Consumer Services                  106
Media & Advertising Services                  103
Banking/Financial Services                     69
Government                                     69
Computer Systems Design and Services           69
Transportation, or Supply Chain                67
Insurance                                      50
Manufacturing                                  48
Higher Education                               42
Energy                                         36
Name: count, dtype: int64